# Site settings
title: Jihwan's Github
timezone: Asia/Seoul
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# url에 임의의 값을 넣으면
# {{site.url}} 사용시 local 환경에서도 지정한 값을 사용한다.

permalink: /:title/

# other links
github_username: jihwanahn
linkedIn_username: jihwanahn
# facebook_username:
# insta_username:
email: k1tstw@tutanota.com

description_footer: ""

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: jihwanahn-github-io

# Statistic Analysis
google_analytics_id: UA-33885705-1 # google analytics id

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# port (default = 4000)
port: 4000

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
# paginate_path: /page:num

future: true
incremental: false
regenerate: true
